# -*- coding: utf-8 -*-
"""31455_Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgqp8bfNHhDOuoOhCPxsfCAm2JzXMBb5
"""

# numerical operations
import numpy as np
# Data handling and analysis
import pandas as pd

df = pd.read_csv("/home/pict/Downloads/melb_data.csv")

# Display first 5 rows
df.head()

# isnull() checks for missing values
# sum() counts missing values column-wise
# Column-wise no. of null values (sum)
df.isnull().sum()

df.isnull()

# Check specific column for missing values
df['BuildingArea'].isnull()

# Check specific column for total no. of missing values
df['BuildingArea'].isnull().sum()

# Replaces missing values with the average value of the column.
df['BuildingArea'].fillna(df['BuildingArea'].mean())

# Replaces missing values with median of the column.
df['BuildingArea'].fillna(df['BuildingArea'].median())

# Replaces missing values with mode of the column.
df['BuildingArea'].fillna(df['BuildingArea'].mode())

# Replaces missing values with a constant value e.g. 0
df['BuildingArea'].fillna(0)

df.describe()

# Shows: column names, data types, non-null values
df.info()

df.shape

# Convert object Type to string
df['Suburb'] = df['Suburb'].astype('string')

df['Suburb'].dtype

# Convert Multiple Specific Columns
cols = ['Suburb', 'Address', 'SellerG']
df[cols] = df[cols].astype('string')

# Convert object to categorical type
df['Type'] = df['Type'].astype('category')

df['Type'].dtype

# Convert float64 to int64 type
df['Postcode'] = df['Postcode'].astype(int)

df['Postcode'].dtype

# Convert Multiple Columns Using Dictionary
df = df.astype({
    'Suburb': 'string',
    'Rooms': 'int',
    'Price': 'float',
    'Type': 'category',
    'Date': 'datetime64[ns]'
})

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Type_LabelEncoded'] = le.fit_transform(df['Type'])

df[['Type', 'Type_LabelEncoded']].head()

onehot = pd.get_dummies(df['Type'], prefix='Type')
# OR Another column
# onehot = pd.get_dummies(df['Method'], prefix='Method')

df = pd.concat([df, onehot], axis=1)

df.head()

dummy = pd.get_dummies(df['Type'], drop_first=True)
# OR Another column
# dummy = pd.get_dummies(df['Regionname'], drop_first=True)

df = pd.concat([df, dummy], axis=1)

df.head()

