# -*- coding: utf-8 -*-
"""Assignment10_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GM-c6Y6FzKHCRcEsOeYxVbgc-jBl2Ojf
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, classification_report, ConfusionMatrixDisplay

df = pd.read_csv("iris.csv")

df.head()

df.shape

df.isnull().sum()

x = df.iloc[: , :-1] # all col except last col
y = df.iloc[: , -1]  # only last col

#split dataset
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 0
)

#create Model
model = GaussianNB()

#train Model
model.fit(x_train,y_train)

# Predict Species

y_pred = model.predict(x_test)

print("Predicted Values : ")
print(y_pred)

#Confussion Matrix

cm = confusion_matrix(y_test,y_pred)
print("Confussion Matrix")
print(cm)

TP = np.diag(cm)
FP = np.sum(cm, axis=0) - TP
FN = np.sum(cm, axis=1) - TP
TN = np.sum(cm) - (TP + FN + FP)
print(TP)
print(FP)
print(FN)
print(TN)

acc = np.sum(TP)/ np.sum(cm)
err = 1-acc
precision = np.mean(TP/(TP+FP))
recall = np.mean(TP/(TP+FN))
print("Accuracy : ", acc)
print("Error Rate : ", err)
print("Precision : ", precision)
print("Recall : ", recall)

print(round(np.trace(cm) / np.sum(cm),2))

disp = ConfusionMatrixDisplay(confusion_matrix = cm)
disp.plot()
plt.show()

