# -*- coding: utf-8 -*-
"""31455_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlg2caixALQsRTq5KxDl0m_PpKIm3-Dk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Load the Academic Performance of Students modified dataset
df = pd.read_csv("StudentsPerformance_modified.csv")

# Display first 5 rows
df.head()

# Dimensions of dataset
df.shape

# Datatypes of each column
df.dtypes

# Display info of dataset
df.info()

# Display statistical summary
df.describe()

# Check for missing values
df.isnull().sum()

# Percentage of missing values
df.isnull().mean() * 100

df['total_marks'] = df['total_marks'].fillna(df['total_marks'].mean())
df['cgpa'] = df['cgpa'].fillna(df['cgpa'].mean())

df.isnull().sum()

df[df['cgpa'] > 10]

df[df['total_marks'] > 300]

numeric_cols = ['dbms_score', 'cns_score', 'os_score', 'total_marks', 'cgpa']

# Boxplot of DBMS Score
plt.figure(figsize=(3,3))
sns.boxplot(y=df['dbms_score'], color='skyblue')
plt.title("Boxplot of DBMS Score")
plt.show()

# Boxplot of CNS Score
plt.figure(figsize=(3,3))
sns.boxplot(y=df['cns_score'], color='lightgreen')
plt.title("Boxplot of CNS Score")
plt.show()

# Boxplot of OS Score
plt.figure(figsize=(3,3))
sns.boxplot(y=df['os_score'], color='salmon')
plt.title("Boxplot of OS Score")
plt.show()

# Boxplot of Total Marks
plt.figure(figsize=(3,3))
sns.boxplot(y=df['total_marks'], color='orchid')
plt.title("Boxplot of Total Marks")
plt.show()

# Boxplot of CGPA
plt.figure(figsize=(3,3))
sns.boxplot(y=df['cgpa'], color='gold')
plt.title("Boxplot of CGPA")
plt.show()

# Calculate z-score for all 5 numeric columns
z_scores = np.abs(stats.zscore(df[numeric_cols]))
outliers_z = (z_scores > 3).sum(axis=0)

# New table created with z-scores for all numeric_cols
z_scores

# displays total no. of outliers for each of 5 columns
outliers_z

z_scores_df = pd.DataFrame(z_scores, columns=numeric_cols)

# Show only rows where at least one column has an outlier
outlier_table = z_scores_df[(z_scores_df > 3).any(axis=1)]
print(outlier_table)

# Step 1: Calculate Q1, Q3, and IQR
Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

print("Q1 (25th Percentile):\n", Q1)
print("\nQ3 (75th Percentile):\n", Q3)
print("\nIQR (Q3 - Q1):\n", IQR)

# Step 2: Calculate Lower and Upper Bounds
lower_bounds = Q1 - 1.5 * IQR
upper_bounds = Q3 + 1.5 * IQR

print("\nLower Bounds:\n", lower_bounds)
print("\nUpper Bounds:\n", upper_bounds)

# Step 3: Count Outliers in Each Column
outlier_counts = ((df[numeric_cols] < lower_bounds) |
                  (df[numeric_cols] > upper_bounds)).sum()

print("\nNumber of Outliers in Each Column:\n", outlier_counts)

# Step 4: Show Actual Outlier Values Column-wise
for col in numeric_cols:
    print(f"\nOutliers in {col}:")
    print(df.loc[(df[col] < lower_bounds[col]) | (df[col] > upper_bounds[col]), col])

df_before = df.copy()

for col in numeric_cols:
    z = np.abs(stats.zscore(df[col]))
    df[col] = np.where(z > 3, df[col].mean(), df[col])

# Check result applied
changed_rows = df_before[numeric_cols] != df[numeric_cols]
print(df.loc[changed_rows.any(axis=1), numeric_cols])

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[col] = np.where(df[col] < lower, lower,
                 np.where(df[col] > upper, upper, df[col]))

plt.figure(figsize=(15,4))

for i, col in enumerate(numeric_cols, 1):
    plt.subplot(1, len(numeric_cols), i)
    sns.histplot(df[col], kde=True)
    plt.title(col)
    plt.tight_layout()

plt.show()

scaler_minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[numeric_cols] = scaler_minmax.fit_transform(df[numeric_cols])
df_minmax.head()

plt.figure(figsize=(15,4))

for i, col in enumerate(numeric_cols, 1):
    plt.subplot(1, len(numeric_cols), i)
    sns.histplot(df_minmax[col], kde=True)
    plt.title(col)
    plt.tight_layout()

plt.show()

scaler_standard = StandardScaler()
df_standard = df.copy()
df_standard[numeric_cols] = scaler_standard.fit_transform(df[numeric_cols])

df_standard.head()

plt.figure(figsize=(15,4))

for i, col in enumerate(numeric_cols, 1):
    plt.subplot(1, len(numeric_cols), i)
    sns.histplot(df_standard[col], kde=True)
    plt.title(col)
    plt.tight_layout()

plt.show()

df[numeric_cols].skew()
