# -*- coding: utf-8 -*-
"""31455_Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JiU13_OpV5AskA8RXUQTZGpGAvtp5Qar
"""

import numpy as np
import pandas as pd

# Load the NBA dataset
df1 = pd.read_csv("nba.csv")

# Display first 5 rows
df1.head()

# Dimensions of dataset
df1.shape

# Datatypes of each column
df1.dtypes

# Display info of dataset
df1.info()

# Display statistical summary
df1.describe()

# Check for missing values
df1.isnull().sum()

# Percentage of missing values
df1.isnull().mean() * 100

df1['Number'] = df1['Number'].fillna(df1['Number'].mean())
df1['Age'] = df1['Age'].fillna(df1['Age'].mean())
df1['Weight'] = df1['Weight'].fillna(df1['Weight'].mean())
df1['Salary'] = df1['Salary'].fillna(df1['Salary'].mean())

# Check for missing values
df1.isnull().sum()

# Group the dataset by Height
height_groups = df1.groupby("Height")

# Display first 5 rows from each height group
height_groups.head()

# Get statistical summary of Weight grouped by Height
height_groups["Weight"].describe()

# Group the dataset by the 'Team' column
team_groups = df1.groupby("Team")

# Display the first 5 rows from each team group
team_groups.head()

# Get statistical summary of Salary for each team
team_groups["Salary"].describe()

# Define the bin ranges for age grouping
bins = [19, 25, 31, 36, 40]

# Define labels for each age group
labels = ["19-24", "25-30", "31-35", "36-40"]

# Create a new column 'AgeGroup' by categorizing Age into bins
df1["AgeGroup"] = pd.cut(df1["Age"], bins=bins, labels=labels)

# Display the updated dataset with the new AgeGroup column
df1

# Count how many players fall into each AgeGroup category
df1["AgeGroup"].value_counts()

# Group the dataset by the 'AgeGroup' column
# observed=True ensures only the groups that actually appear in the data are shown
age_groups = df1.groupby("AgeGroup", observed=True)

# Get statistical summary of Salary for each AgeGroup
age_groups["Salary"].describe()

# Load the Iris dataset
df2 = pd.read_csv("Iris.csv")

# Display first 5 rows
df2.head()

# Dimmensions of dataset
df2.shape

# Datatypes of each column
df2.dtypes

# Display info of dataset
df2.info()

# Display statistical summary
df2.describe()

# Check missing values
df2.isnull().sum()

# Filter rows where Species is 'Iris-setosa'
setosa = df2[df2['Species'] == 'Iris-setosa']

# Filter rows where Species is 'Iris-versicolor'
versicolor = df2[df2['Species'] == 'Iris-versicolor']

# Filter rows where Species is 'Iris-virginica'
virginica = df2[df2['Species'] == 'Iris-virginica']

# Print descriptive statistics for Iris-setosa species
print("Iris-setosa statistics:")
print(setosa.describe())

# Print descriptive statistics for Iris-versicolor species
print("\nIris-versicolor statistics:")
print(versicolor.describe())

# Print descriptive statistics for Iris-virginica species
print("\nIris-virginica statistics:")
print(virginica.describe())

