# -*- coding: utf-8 -*-
"""assign7_31444.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jX4cRaraCZXTFHrjl54RRA2groUr5g7l

## A7

<b>Text Analytics</b>

- Extract Sample document and apply following document preprocessing methods:

  
    Tokenization, POS Tagging, stop words removal, Stemming and Lemmatization.
    
- Create representation of document by calculating Term Frequency and Inverse Document Frequency

<b>1) Import Required Libraries</b>
"""

# Import required libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag
from sklearn.feature_extraction.text import TfidfVectorizer

# Download necessary datasets (run only once)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

"""<b>2) Load Given Text Files</b>"""

# Load the given text files
with open("PRINCIPALS_MESSAGE.txt", "r", encoding="utf-8") as f:
    doc1 = f.read()

with open("DIRECTORS_MESSAGE.txt", "r", encoding="utf-8") as f:
    doc2 = f.read()

# Combine documents into a list
documents = [doc1, doc2]

print("Documents Loaded Successfully!")

print("Document 1 Sample:\n", doc1[:300])
print("\nDocument 2 Sample:\n", doc2[:300])

"""<b>3) Tokenization</b>

- Tokenization is the process of breaking text into smaller units called tokens (words).
- Example: "Hello World" → ["Hello", "World"]
"""

# Tokenization
tokens_doc1 = word_tokenize(doc1)
tokens_doc2 = word_tokenize(doc2)

print("\nTokens from Document 1:")
print(tokens_doc1[:50])

print("\nTokens from Document 2:")
print(tokens_doc2[:50])

"""<b>4) POS Tagging</b>

<b>Part-of-Speech Tagging</b>

POS tagging assigns grammatical labels to each word such as:
- Noun (NN)
- Verb (VB)
- Adjective (JJ)

Example:

"I love coding" → [('I', PRP), ('love', VB), ('coding', NN)]

<b>POS Tag Full Forms</b>

| POS Tag | Full Form                  | Meaning                     |
|--------|---------------------------|-----------------------------|
| NN     | Noun, singular            | General noun                |
| NNS    | Noun, plural              | Plural noun                 |
| NNP    | Proper Noun, singular     | Name of person/place        |
| NNPS   | Proper Noun, plural       | Plural proper noun          |
| VB     | Verb (base form)          | Base verb                   |
| VBD    | Verb (past tense)         | Past tense verb             |
| VBG    | Verb (gerund/present participle) | Verb ending with -ing |
| VBN    | Verb (past participle)    | Past participle form        |
| VBP    | Verb (present tense)      | Present tense verb          |
| VBZ    | Verb (3rd person singular)| He/She/It form              |
| JJ     | Adjective                 | Describes noun              |
| JJR    | Adjective (comparative)   | Bigger, faster              |
| JJS    | Adjective (superlative)   | Biggest, fastest            |
| RB     | Adverb                    | Describes verb              |
| RBR    | Adverb (comparative)      | Faster                      |
| RBS    | Adverb (superlative)      | Fastest                     |
| IN     | Preposition               | in, on, at                  |
| DT     | Determiner                | the, a, an                  |
| PRP    | Personal Pronoun          | he, she, it                 |
| PRP$   | Possessive Pronoun        | his, her, their             |
| CC     | Coordinating Conjunction  | and, but, or                |
"""

# POS Tagging
pos_tags1 = pos_tag(tokens_doc1)
pos_tags2 = pos_tag(tokens_doc2)

print("\nPOS Tags1:")
print(pos_tags1[:50])

print("\nPOS Tags2:")
print(pos_tags2[:50])

"""<b>5) Stop Words Removal</b>

- Stop words are common words like "is", "the", "and" which do not add much meaning.
- Removing them helps improve processing efficiency.
"""

# Stop words removal
stop_words = set(stopwords.words('english'))

filtered_tokens1 = [word for word in tokens_doc1 if word.lower() not in stop_words]
filtered_tokens2 = [word for word in tokens_doc2 if word.lower() not in stop_words]

print("\nAfter Stop Word Removal1:")
print(filtered_tokens1[:50])

print("\nAfter Stop Word Removal2:")
print(filtered_tokens2[:50])

"""<b>6) Stemming</b>

- Stemming reduces words to their root form.
- By removing suffixes such as -ing, -ed, -ly, -ion, etc.
- Example:
    - "running", "runs" → "run"
    - “eating,” “eats,” “eaten” → “eat.”
"""

# Stemming
stemmer = PorterStemmer()

stemmed_words1 = [stemmer.stem(word) for word in filtered_tokens1]
stemmed_words2 = [stemmer.stem(word) for word in filtered_tokens2]

print("\nStemmed Words1:")
print(stemmed_words1[:50])

print("\nStemmed Words2:")
print(stemmed_words2[:50])

"""<b>7) Lemmatization</b>

- Lemmatization is the process of reducing words to their base or dictionary form (lemma) using linguistic knowledge and vocabulary.
- It converts words into their meaningful base form.
- Unlike stemming, lemmatization produces meaningful and grammatically correct word
- Example:
    - rocks : rock
    - corpora : corpus
    - better : good
"""

# Lemmatization
lemmatizer = WordNetLemmatizer()

lemmatized_words1 = [lemmatizer.lemmatize(word) for word in filtered_tokens1]
lemmatized_words2 = [lemmatizer.lemmatize(word) for word in filtered_tokens2]

print("\nLemmatized Words1:")
print(lemmatized_words1[:50])

print("\nLemmatized Words2:")
print(lemmatized_words2[:50])

"""<hr>

<h3>TF-IDF</h3>

- Term Frequency - Inverse Document Frequency (TF-IDF) is a widely used statistical method in natural language processing and information retrieval.
- It measures how important a term is within a document relative to a collection of documents (i.e., relative to a corpus).
- Words within a text document are transformed into importance numbers by a text vectorization process.
- There are many different text vectorization scoring schemes, with TF-IDF being one of the most common.

[Source](https://www.learndatasci.com/glossary/tf-idf-term-frequency-inverse-document-frequency/)

<hr>

<b>- Term Frequency (TF)</b>

TF of a term or word is the number of times the term appears in a document compared to the total number of words in the document.

$TF = \frac{term}{total}$

Where:
- $term$ is the number of times the specific term appears in the document.
- $total$ is the total number of terms in the document.

<hr>

<b>- Inverse Document Frequency (IDF)</b>

IDF is a measure used in information retrieval and text mining to quantify the importance of a term within a collection of documents.

$IDF(t) = \log(\frac{N}{DF(t)})$

Where:
- $N$ is the number of documents.
- $DF(t)$ is the number of documents containing the term t (i.e., the document frequency of t).

<hr>

<b>8) TF-IDF Representation</b>

TF (Term Frequency):
How often a word appears in a document.

IDF (Inverse Document Frequency):
How important a word is across documents.

<b>TF-IDF = TF × IDF</b>

Important words get higher scores.
"""

# Combine both documents
documents = [doc1, doc2]

vectorizer = TfidfVectorizer(stop_words='english')

tfidf_matrix = vectorizer.fit_transform(documents)

feature_names = vectorizer.get_feature_names_out()

import numpy as np
np.set_printoptions(threshold=np.inf)
print("\nFeatures Words: \n", feature_names)
print("\nTF-IDF Matrix: \n", tfidf_matrix.toarray())

"""Display TF-IDF"""

import pandas as pd

df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

# Show top 10 words as a table
for i in range(len(df)):
    print(f"\nTop words in Document {i+1}:\n")
    display(df.iloc[i].sort_values(ascending=False).head(10).to_frame(name="TF-IDF Score"))

"""<hr>

<h3>Inference</h3>

<b>Principal's Message:</b>
- Focuses on:
    - Institution history
    - Vision & mission
    - Student development
- Keywords (TF-IDF):
    - PICT, students, education, faculty, excellence

<b>Director's Message:</b>
- Focuses on:
    - Achievements
    - Placements
    - Activities & opportunities
- Keywords:
    - students, research, placement, activities, innovation

<b>From TF-IDF analysis:</b>

- Both documents emphasize "PICT" and "students" as core themes.
- Principal’s message focuses more on vision, education, and development.
- Director’s message highlights achievements, placements, and activities.
- TF-IDF successfully identifies important distinguishing words in both documents.

Thus, TF-IDF helps in understanding document importance and key topics effectively.
"""
