# -*- coding: utf-8 -*-
"""Asignment8_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzN8xx7CzwDjWPPJRmpzDwz2pkyvSCWJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("BostonHousing.csv")

df.shape

df.head()

df.isnull().sum()

df['rm'] = df['rm'].fillna(df['rm'].mean())

df.isnull().sum()

plt.figure(figsize=(14, 6))
sns.boxplot(data=df)
plt.title("Boxplot for outliers detection")

#remove all the outliers

for col in df.columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3-q1
    low = q1-1.5*iqr
    high = q3+1.5*iqr
    df[col] = df[col].clip(lower = low, upper = high)

plt.figure(figsize=(14, 6))
sns.boxplot(data=df)

X = df.drop('medv', axis=1)
y = df['medv']

X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

