# -*- coding: utf-8 -*-
"""Asssignment9_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaJz4DRu95k2N_vUjJL73yAMmCt80Kxz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

df = pd.read_csv("Social_Network_Ads.csv")
df.shape

df.head()

df.isnull().sum()

print(df["Age"].describe())

sns.boxplot(data=df) # for outliers detection

sns.boxplot(data=df["Age"])

sns.boxplot(data=df["EstimatedSalary"])

X = df[['Age','EstimatedSalary']].values
y = df['Purchased']

y

X_train, X_test, y_train, y_test = train_test_split( X,y, train_size = 0.2, random_state = 42)

Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

TN,FP,FN,TP = cm.ravel()
print("TP : ", TP)
print("TN : ", TN)
print("FP : ", FP)
print("FN : ", FN)

accuracy = (TN+TP)/(TN+TP+FN+FP)
error = 1-accuracy
precision = TP/(TP+FP)
recall = TP/(TP/FN)
print("Accuracy : ", accuracy)
print("Error : ", error)
print("Precision : ", precision)
print("Recall : ", recall)

